### ISSUE TITLE
Excellent extension!

### ISSUE THREAD

**Issue by bbugh** [johnathanludwig/vscode-fileswitcher#1]
This isn't an issue but I don't want to make a Microsoft account to tell you. This extension rocks! I tried a bunch of other switchers before stumbling on this one, and it's simple and elegant. Thanks for making it!

**Comment by johnathanludwig** [comment]
Thanks a lot, I really appreciate it! I also tried quite a few switchers and they were always to code or framework specific which is what led me to make this.
